# Generated by Django 5.1.2 on 2024-10-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_order_count_user_rating_user_rating_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='budget',
            field=models.PositiveIntegerField(default=5000),
        ),
    ]
