# Generated by Django 5.1.2 on 2024-10-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('applicant', 'Applicant'), ('supplier', 'Supplier'), ('recipient', 'Recipient')], max_length=10),
        ),
    ]
