# Generated by Django 5.1.2 on 2024-10-22 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_budget_service_order_count_service_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='budget',
        ),
    ]
